# Generated by Django 4.2.4 on 2023-09-21 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_comment_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment_by',
            field=models.CharField(default='Anonymous', max_length=100),
        ),
    ]
